name: php-redirect-app
type: "php:8.1"  # Specify the PHP version

# Web application configuration
web:
    locations:
        "/":
            root: "index.php"  # Points to the index.php file in the root directory
            allow: true
