# routes.yaml
# This is an optional file for custom URL routing configuration on Platform.sh

# Define a catch-all route for the base URL
"https://<project-name>.platform.sh/*":
  type: upstream
  upstream: "app:http"
